"""added repo_id

Revision ID: 13e10adf8e27
Revises: 8a518189662f
Create Date: 2024-05-30 02:50:32.704308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e10adf8e27'
down_revision: Union[str, None] = '8a518189662f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_stats', sa.Column('repo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repo_stats', 'repo_config', ['repo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo_stats', type_='foreignkey')
    op.drop_column('repo_stats', 'repo_id')
    # ### end Alembic commands ###
