"""added filepath to NodeModel and name to TestModuleModel

Revision ID: 2ee3ecc05c40
Revises: df1d20e2c832
Create Date: 2024-05-01 11:12:35.483141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee3ecc05c40'
down_revision: Union[str, None] = 'df1d20e2c832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('testfilepath', sa.String(), nullable=True))
    op.add_column('test_modules', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_modules', 'name')
    op.drop_column('nodes', 'testfilepath')
    # ### end Alembic commands ###
