"""fixed some relations

Revision ID: 3e1fd387befe
Revises: d0c885df6cfa
Create Date: 2024-05-02 16:20:44.582061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1fd387befe'
down_revision: Union[str, None] = 'd0c885df6cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('target_code_id', sa.Integer(), nullable=True))
    op.drop_constraint('nodes_repo_id_fkey', 'nodes', type_='foreignkey')
    op.drop_constraint('nodes_test_module_id_fkey', 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'target_code', ['target_code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'nodes', 'repo_config', ['repo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'nodes', 'test_modules', ['test_module_id'], ['id'], ondelete='CASCADE')
    op.add_column('target_code', sa.Column('test_module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'target_code', 'test_modules', ['test_module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('target_code', 'class_scope')
    op.drop_column('target_code', 'func_scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_code', sa.Column('func_scope', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('target_code', sa.Column('class_scope', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'target_code', type_='foreignkey')
    op.drop_column('target_code', 'test_module_id')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key('nodes_test_module_id_fkey', 'nodes', 'test_modules', ['test_module_id'], ['id'])
    op.create_foreign_key('nodes_repo_id_fkey', 'nodes', 'repo_config', ['repo_id'], ['id'])
    op.drop_column('nodes', 'target_code_id')
    # ### end Alembic commands ###
