"""renamed feedback to decide

Revision ID: 4182504b989a
Revises: 2bc1adebc872
Create Date: 2024-05-20 02:06:40.051434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4182504b989a'
down_revision: Union[str, None] = '2bc1adebc872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('augment_test_results', sa.Column('decide', sa.Integer(), nullable=True))
    op.drop_column('augment_test_results', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('augment_test_results', sa.Column('feedback', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('augment_test_results', 'decide')
    # ### end Alembic commands ###
