"""added main and remote to repoconfig

Revision ID: 486ee62cfdb2
Revises: 53cfcb81976f
Create Date: 2024-05-13 18:00:08.309289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486ee62cfdb2'
down_revision: Union[str, None] = '53cfcb81976f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_config', sa.Column('remote', sa.String(), nullable=True))
    op.add_column('repo_config', sa.Column('main', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_config', 'main')
    op.drop_column('repo_config', 'remote')
    # ### end Alembic commands ###
