"""added auto_gen to test_modules


Revision ID: 4be689188190
Revises: e3cae2f0fb3e
Create Date: 2024-05-16 22:49:42.800773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be689188190'
down_revision: Union[str, None] = 'e3cae2f0fb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_modules', sa.Column('auto_gen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_modules', 'auto_gen')
    # ### end Alembic commands ###
