"""added session_id to TestResults

Revision ID: 4bf808259948
Revises: 7ab0269403a8
Create Date: 2024-05-27 15:02:17.441346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf808259948'
down_revision: Union[str, None] = '7ab0269403a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('augment_test_results', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('augment_test_results', 'session_id')
    # ### end Alembic commands ###
