"""Added repo_model

Revision ID: 5a9b1afb76e3
Revises: e635c218de2a
Create Date: 2024-04-23 21:45:56.527438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9b1afb76e3'
down_revision: Union[str, None] = 'e635c218de2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('forked_url', sa.String(), nullable=True),
    sa.Column('cloned_folders', sa.String(), nullable=True),
    sa.Column('source_folder', sa.String(), nullable=True),
    sa.Column('python_conf', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cowboy_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_config')
    # ### end Alembic commands ###
