"""updated range on TargeCodeModel

Revision ID: 68e7bf63522d
Revises: 3e1fd387befe
Create Date: 2024-05-02 16:26:07.546110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e7bf63522d'
down_revision: Union[str, None] = '3e1fd387befe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_code', sa.Column('start', sa.Integer(), nullable=True))
    op.add_column('target_code', sa.Column('end', sa.Integer(), nullable=True))
    op.drop_column('target_code', 'range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_code', sa.Column('range', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('target_code', 'end')
    op.drop_column('target_code', 'start')
    # ### end Alembic commands ###
