"""added augmentTestResult models

Revision ID: 7f8df6212797
Revises: 4be689188190
Create Date: 2024-05-19 14:22:05.027883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8df6212797'
down_revision: Union[str, None] = '4be689188190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('augment_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('test_case', sa.String(), nullable=True),
    sa.Column('cov_plus', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('testfile', sa.String(), nullable=True),
    sa.Column('classname', sa.String(), nullable=True),
    sa.Column('test_module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_module_id'], ['test_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('augment_test_results')
    # ### end Alembic commands ###
