"""added cascade delete from TestModule -> AugmentTestResults

Revision ID: 87a33ce1322a
Revises: 529e2719b577
Create Date: 2024-06-20 19:51:54.939523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a33ce1322a'
down_revision: Union[str, None] = '529e2719b577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('augment_test_results_test_module_id_fkey', 'augment_test_results', type_='foreignkey')
    op.create_foreign_key(None, 'augment_test_results', 'test_modules', ['test_module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'augment_test_results', type_='foreignkey')
    op.create_foreign_key('augment_test_results_test_module_id_fkey', 'augment_test_results', 'test_modules', ['test_module_id'], ['id'])
    # ### end Alembic commands ###
