"""added RepoStats (actually)

Revision ID: 8a518189662f
Revises: 3c7b1822da96
Create Date: 2024-05-30 01:32:54.606182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a518189662f'
down_revision: Union[str, None] = '3c7b1822da96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('accepted_tests', sa.Integer(), nullable=True),
    sa.Column('rejected_tests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_stats')
    # ### end Alembic commands ###
