"""addde language field to RepoConfig model

Revision ID: 8cbcddf29c9e
Revises: 4182504b989a
Create Date: 2024-05-20 18:57:41.319324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbcddf29c9e'
down_revision: Union[str, None] = '4182504b989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_config', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_config', 'language')
    # ### end Alembic commands ###
