"""added coverage table

Revision ID: b9671daa1ec7
Revises: 486ee62cfdb2
Create Date: 2024-05-16 01:06:36.599380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9671daa1ec7'
down_revision: Union[str, None] = '486ee62cfdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('covered_lines', sa.String(), nullable=False),
    sa.Column('missing_lines', sa.String(), nullable=False),
    sa.Column('stmts', sa.Integer(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('covered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('target_code', sa.Column('coverage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'target_code', 'coverage', ['coverage_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target_code', type_='foreignkey')
    op.drop_column('target_code', 'coverage_id')
    op.drop_table('coverage')
    # ### end Alembic commands ###
