"""added backref from TMModel to Nodes

Revision ID: d428a766b0ef
Revises: 2ee3ecc05c40
Create Date: 2024-05-01 21:37:52.458142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd428a766b0ef'
down_revision: Union[str, None] = '2ee3ecc05c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
