"""added repoid to coverage

Revision ID: e3cae2f0fb3e
Revises: b9671daa1ec7
Create Date: 2024-05-16 02:32:20.376283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cae2f0fb3e'
down_revision: Union[str, None] = 'b9671daa1ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage', sa.Column('repo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coverage', 'repo_config', ['repo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coverage', type_='foreignkey')
    op.drop_column('coverage', 'repo_id')
    # ### end Alembic commands ###
